language: objective-c
git:
  submodules: false
# Mac-OS-X uses BSD's gettext, which lacks "autopoint".
# HomeBrew's gettext has autopoint, but it is not added to the path
# by default (because it conflicts with the BSD's one).
# Add the path of homebrew's gettext, so 'autopoint' will be found.
env:
  global:
  - PATH=/usr/local/opt/gettext/bin:$PATH
compiler:
  - clang
before_install:
  - brew update
  - brew install help2man
  - brew install md5sha1sum
  - brew install valgrind
  - brew install xz
  - brew install lcov
  - brew install gettext
  - wget ftp://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.bz2
  - tar -xjf sed-4.2.2.tar.bz2
  - "( cd sed-4.2.2 ; ./configure && make && sudo make install )"
  - which automake
  - automake --version
  - which autoconf
  - autoconf --version
  - which autopoint
  - autopoint --version
  - which gettext
  - gettext --version
  - which autoreconf
  - autoreconf --version
script:
- "( git fetch --unshallow ; true )"
- ls -l
- ./bootstrap
- ls -l
- git describe --always
- ./build-aux/git-version-gen .tarball-version
- ./configure
- make
- make check VERBOSE=yes
- cat tests/calc-show-env.sh.log ; true
- cat ./test-suite.log ; true
- make dist
- make distcheck
after_success:
- ./build-aux/make_bin_dist.sh
- ls -l ./bin/
- md5sum ./bin/*.tar.gz
- sha1sum ./bin/*.tar.gz
- ( FILE=$(basename $(ls ./bin/calc-*.tar.gz)) ; echo "--BIN-DIST-START--:$FILE" ; cat ./bin/calc*.tar.gz | base64 | fold -w 400 ; echo "--BIN-DIST-END--" )
- ./build-aux/rebuild-coverage.sh
